export function Security() {
  return <article className="reading-page">
    <p className="eyebrow">How the service is protected</p><h1>Security</h1>
    <p className="page-description">A short description of the protections built into this project and the controls an operator must provide.</p>
    <section><h2>Moderator access</h2><p>Moderator API routes require a shared Bearer token configured through an environment variable. The browser dashboard does not replace this server-side check. Use HTTPS and keep the token out of source control.</p></section>
    <section><h2>Report codes and validation</h2><p>Case codes are generated using cryptographically secure random bytes and are separate from internal database IDs. The API validates report fields, categories, status values and allowed status transitions.</p></section>
    <section><h2>Evidence handling</h2><p>Uploads support PDF, PNG, JPG/JPEG and UTF-8 TXT, with a configured size limit that defaults to 5 MiB. The backend validates the declared MIME type and filename extension, checks binary files against file signatures where applicable, and validates text files as UTF-8. Files are first written to temporary storage and scanned through ClamAV before being moved to persistent evidence storage. Malware detections are rejected, and uploads also fail closed if ClamAV is unavailable or the scan fails. Files are stored under generated names, and only authenticated moderators can download evidence.</p><p className="reading-note">These controls do not guarantee perfect anonymity or that a file is harmless. Infrastructure may retain connection data, and report text or uploaded files may contain identifying information.</p></section>
    <section><h2>Operations matter</h2><p>Database credentials and moderator secrets must be supplied through environment configuration. The application does not include a production secrets manager, database encryption policy, backups, or retention automation. Operators should use TLS, restrict database and evidence-volume access, and set an appropriate retention policy.</p></section>
  </article>;
}
